
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shared-database-discriminator-column?currentSchema=saas
    username: postgres
    password: postgres

  main:
    banner-mode: off

server:
  port: 9000
  servlet:
    context-path: /api
